# Generated by Django 3.2.16 on 2026-05-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_auto_20260514_1412"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="posts/", verbose_name="Изображение"
            ),
        ),
    ]
